export const PROVISION_STAGES = {
  PAYMENT_CONFIRMED: "PAYMENT_CONFIRMED",
  CONNECTING_PANEL: "CONNECTING_PANEL",
  CREATING_CUSTOMER: "CREATING_CUSTOMER",
  CREATING_WEBSPACE: "CREATING_WEBSPACE",
  FINALIZING: "FINALIZING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
} as const;

export type ProvisionStage = (typeof PROVISION_STAGES)[keyof typeof PROVISION_STAGES];

export const PROVISION_STAGE_ORDER: ProvisionStage[] = [
  PROVISION_STAGES.PAYMENT_CONFIRMED,
  PROVISION_STAGES.CONNECTING_PANEL,
  PROVISION_STAGES.CREATING_CUSTOMER,
  PROVISION_STAGES.CREATING_WEBSPACE,
  PROVISION_STAGES.FINALIZING,
  PROVISION_STAGES.COMPLETED,
];
