import type { Config } from "tailwindcss";
import animate from "tailwindcss-animate";

const config: Config = {
  darkMode: ["class"],
  content: ["./src/**/*.{ts,tsx}", "../../packages/ui/src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "var(--bg)",
        foreground: "var(--label)",
        surface: "var(--bg-grouped)",
        "surface-container-lowest": "var(--bg-elevated)",
        "surface-container-low": "var(--bg-secondary)",
        "surface-container-high": "var(--bg-secondary)",
        "surface-container-highest": "var(--bg-secondary)",
        "surface-container": "var(--bg-secondary)",
        "surface-bright": "var(--bg-elevated)",
        "surface-dim": "var(--bg-grouped)",
        "surface-variant": "var(--bg-secondary)",
        "surface-tint": "var(--accent)",
        "on-background": "var(--label)",
        "on-surface": "var(--label)",
        "on-surface-variant": "var(--label-secondary)",
        primary: "var(--accent)",
        "primary-dark": "var(--accent-hover)",
        "on-primary": "#ffffff",
        "primary-container": "color-mix(in srgb, var(--accent) 12%, var(--bg-elevated))",
        "on-primary-container": "var(--accent)",
        "primary-fixed": "color-mix(in srgb, var(--accent) 8%, var(--bg))",
        "on-primary-fixed": "var(--label)",
        secondary: "var(--accent)",
        "on-secondary": "#ffffff",
        "secondary-container": "color-mix(in srgb, var(--accent) 15%, var(--bg-elevated))",
        "on-secondary-container": "var(--label)",
        "secondary-fixed": "var(--fill)",
        "on-secondary-fixed": "var(--label)",
        tertiary: "var(--label)",
        "on-tertiary": "var(--bg)",
        outline: "var(--separator)",
        "outline-variant": "var(--separator)",
        error: "var(--danger)",
        "on-error": "#ffffff",
        "error-container": "color-mix(in srgb, var(--danger) 12%, var(--bg))",
        "on-error-container": "var(--danger)",
        "inverse-surface": "var(--label)",
        "inverse-on-surface": "var(--bg)",
        "inverse-primary": "var(--accent)",
        "panel-bg": "var(--bg-grouped)",
      },
      borderRadius: {
        apple: "var(--radius-md)",
        "apple-lg": "var(--radius-lg)",
        "apple-xl": "var(--radius-xl)",
        pill: "980px",
      },
      spacing: {
        "stack-lg": "48px",
        "margin-tablet": "32px",
        "stack-sm": "12px",
        gutter: "32px",
        unit: "8px",
        "container-max": "1080px",
        "stack-md": "24px",
        "margin-desktop": "48px",
        "margin-mobile": "20px",
      },
      maxWidth: {
        "container-max": "1080px",
      },
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          '"SF Pro Display"',
          '"SF Pro Text"',
          "system-ui",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
        jakarta: [
          "-apple-system",
          "BlinkMacSystemFont",
          '"SF Pro Display"',
          "system-ui",
          "sans-serif",
        ],
        inter: [
          "-apple-system",
          "BlinkMacSystemFont",
          '"SF Pro Text"',
          "system-ui",
          "sans-serif",
        ],
        geist: [
          "-apple-system",
          "BlinkMacSystemFont",
          '"SF Pro Text"',
          "system-ui",
          "sans-serif",
        ],
      },
      fontSize: {
        "body-md": ["17px", { lineHeight: "1.47", fontWeight: "400" }],
        "body-lg": ["19px", { lineHeight: "1.47", fontWeight: "400" }],
        "label-sm": ["13px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-lg": ["28px", { lineHeight: "1.14", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "1.1", letterSpacing: "-0.025em", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.05", letterSpacing: "-0.03em", fontWeight: "600" }],
        "display-lg": ["56px", { lineHeight: "1.05", letterSpacing: "-0.035em", fontWeight: "600" }],
      },
      boxShadow: {
        apple: "var(--shadow-sm)",
        "apple-md": "var(--shadow-md)",
      },
    },
  },
  plugins: [animate],
};

export default config;
